[package]
name = "rustyweather"
version = "0.2.0"
authors = ["Jamie Phillips <cphill11@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.8"
scraper  = "0.12.0"
failure = "0.1.7"
exitfailure = "0.5.1"
futures = "0.3"