[package]
name = "rustyweather"
version = "0.1.0"
authors = ["Jamie Phillips <cphill11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = "0.9.19"
scraper  = "0.10.1"